const { Router } = require("express")
const { listarCategorias } = require("./controladores/categorias")
const { cadastrarUsuario, login, detalharUsuario, atualizarUsuario } = require("./controladores/usuarios")
const { schemaUsuario } = require("./Schemas/usuarios")
const { validarCorpoRequisicao } = require("./intermediarios/validarCorpoRequisicao")
const { verificarUsuarioLogado } = require("./intermediarios/autenticador")
const { cadastrarProduto, listarProduto, detalharProduto } = require("./controladores/produtos")
const { schemaProduto } = require("./Schemas/produtos")
const { schemaCliente } = require("./Schemas/clientes")
const { cadastrarCliente, atualizarCliente, detalharCliente } = require("./controladores/clientes")
const rotas = Router()

rotas.get("/categoria", listarCategorias)
rotas.post("/usuario", validarCorpoRequisicao(schemaUsuario), cadastrarUsuario)
rotas.post("/login", login)
rotas.use(verificarUsuarioLogado)
rotas.get("/usuario", detalharUsuario)
rotas.put("/usuario", validarCorpoRequisicao(schemaUsuario), atualizarUsuario)
rotas.post("/produto", validarCorpoRequisicao(schemaProduto), cadastrarProduto)
rotas.get("/produto", listarProduto)
rotas.get("/produto/:id", detalharProduto)
rotas.post("/cliente", validarCorpoRequisicao(schemaCliente), cadastrarCliente)
rotas.get("/cliente/:id", detalharCliente)
rotas.put("/cliente/:id", validarCorpoRequisicao(schemaCliente), atualizarCliente)


module.exports = rotas